version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Cbay1988

  mongo-express:
    image: mongo-express
    container_name: mongodb_mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Cbay1988

  scrapyd:
    image: registry.cn-shenzhen.aliyuncs.com/sim_cat/scrapyd
    container_name: scrapyd
    restart: always
    ports:
      - 6800:6800
  
  spiderkeeper:
    image: registry.cn-shenzhen.aliyuncs.com/sim_cat/spiderkeeper
    container_name: spiderkeeper
    restart: always
    ports:
      - 5000:5000
    environment:
      SERVER: http://172.29.58.67:6800
      TZ: Asia/Shanghai
    volumes:
      - ~/spiderkeeper:/db
    depends_on:
      - scrapyd

  bugly-flask:
    image: registry.cn-shenzhen.aliyuncs.com/sim_cat/bugly-flask:latest
    build: ./BuglyFlask
    container_name: bugly-flask
    restart: always
    environment:
      MONGODB_SERVER: "192.168.2.1"
    ports:
      - 5100:5000
    depends_on:
      - mongo
  
  nginx:
    image: nginx:1.15.5-alpine
    container_name: nginx
    restart: always
    ports: 
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  
  bugly-vue:
    image: registry.cn-shenzhen.aliyuncs.com/sim_cat/bugly-vue:latest
    build: ./BuglyVueJs/bugly-vue
    container_name: bugly-vue
    restart: always
    ports: 
      - 8082:80


volumes:
  buglgflask:
